### ISSUE TITLE
Provide a way to define schemas

### ISSUE THREAD

**Issue by Markus-Ende** [nbeach/ng-unit#52]
Currently it is not possible to provide a schema (or am I missing something?). Especially NO_ERRORS_SCHEMA is important to create shallow component test.

Option 1:

Add a general schemas function to TestBuilder, like the one for providers: `testComponent(MyComponent).schemas([NO_ERRORS_SCHEMA])` 

Option 2:

Explicitly add a function to activate shallow component testing. Something like `testComponent(MyComponent).shallow()`.

Thanks for the great library, by the way!

**Comment by Markus-Ende** [comment]
Maybe option 1 is more flexible, so you can use CUSTOM_ELEMENTS_SCHEMA or NO_ERRORS_SCHEMA.

**Comment by Markus-Ende** [comment]
I created the small PR for you. Feel free to give feedback / change things. If you have any other ideas/plans let me know, I would like to contribute as discussed via e-mail.

**Comment by nbeach** [comment]
The approach I've taken to accomplish a "shallow" rendering is to mock child components using testBuilder.mock([SomeChild]), rather than provide the NO_ERRORS_SCHEMA. The benefit I see here is that mocking the children allows you to assert:

the child components properly receive input bindings
the component under test responds to output events emitted by it's children
if/how instance methods on the child component class (accessed via @ViewChild) are called and what they return
When the NO_ERRORS_SCHEMA is used the children are essentially ignored, and (to my knowledge) you can't test any interactions with the child components. Are there scenarios you know of where NO_ERRORS_SCHEMA provide advantages vs the mocking or allows testing of the interactions in ways I'm not aware of?

Beyond the case at hand it seems reasonable that setting the schema could be useful though for some use cases.

**Comment by Markus-Ende** [comment]
You're right, mocking is great when testing interaction between components, which is impossible with the NO_ERRORS_SCHEMA. But if I'm just testing some internals of my component that is not necessary. I try to keep my test setup as simple as possible. 

You can also use the NO_ERRORS_SCHEMA to ignore directives that are not needed for a test case. Currently you're forced to use real instances because they can't be mocked.

And last but not least it's a test performance issue. I worked on large code bases with many component tests and greatly accelerated test runtime by using shallow tests.

But as you said, the best would be to just enable setting any schemas. Let the user decide on his testing style 🙂

**Comment by nbeach** [comment]
All fair points. I'm onboard. :)

**Comment by nbeach** [comment]
Implemented by #53
