### ISSUE TITLE
Error: You cannot configure a test while a test already is in progress

### ISSUE THREAD

**Issue by Markus-Ende** [nbeach/ng-unit#57]
Hi,

After updating to version 0.9.0, I always get the "You cannot configure a test while a test already is in progress" Error.
I made stackblitz to reproduce it: https://stackblitz.com/edit/ng-unit-in-progress-error

Nothing special there, just two test cases. Seems to be an issue with the in-progress-flag.

Regards
Markus

Edit: corrected link

**Comment by nbeach** [comment]
I don't see ng-unit used anywhere in that example? Are you including a `teardown()` call in an `afterEach()` in your test suite?

In the last release logic was added to give better feedback when a user tries to modify test setup after the test has begun. This required that teardown no longer be a strictly optional step.

**Comment by Markus-Ende** [comment]
Oh, sorry, posted the wrong link.
And you're right, I didn't call `teardown()`, because I didn't realize that I have to. Is there some other way to achieve better feeback? It's really easy to forget this and also is not very intuitive in my opinion...

**Comment by Markus-Ende** [comment]
Could'nt we reset everything in `TestBuilder#begin()` right before initializing the new TestBed? Then calling `teardown()` manually would only be necessary if the `TestBuilder` is not used

**Comment by Markus-Ende** [comment]
Tried to add it to the TestBuilder constructor: https://github.com/Markus-Ende/ng-unit/tree/avoid-aftereach
I can see now that it's not so easy, because with this approach, the "You must first start a test using .begin() before using this method" error message won't work anymore because of the static dependency to `_subjectElement` query-functions like `element()`.

The only way I could image right now to make this work, is to change `TestBuilder#build()` to not return `T` but another builder that gives access to those query-functions.

Tests would then look something like this:
```
const testSetup = testComponent(SubjectComponent)
    .mock([ChildComponent])
    .begin()

  expect(testSetup.component("#transcluded").someInput).to.equal("")
```

The advantage of this would be to force users of the API to use it correctly, instead of throwing error messages.

**Comment by nbeach** [comment]
I had initially experimented with attaching many methods to a `TestContext` object returned by `.build()` much like you describe. Ultimately I decided against it primarily because having multiple test contexts implies that multiple tests can be built/executed in parallel which we cannot support due to TestBed limitations, and doing so would still have state validation scenarios to prevent the user from trying to start multiple tests at the same time. Also it felt syntactically noisy to have to call every test method from the context object.

Perhaps there is a middle ground for the error feedback? We could allow subsequent `testComponent()` calls to automatically tear down an existing test, but keep the other errors around `.onOutput()`, `.mock()`, etc while a test is in progress. Does that seem reasonable?

I appreciate the thoughtful feedback!

**Comment by nbeach** [comment]
Here is an implementation #58

**Comment by Markus-Ende** [comment]
Ok, works for me :-)
